name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: ğŸ“¦ Install Yarn
        run: npm install yarn

      - name: â¬‡ï¸ Install Dependencies
        run: yarn install

      - name: ğŸš€ Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn cy:run:chrome
